background = #eff1f5
foreground = #4c4f69
cursor-color = #b4462d
selection-background = #b4462d
selection-foreground = #eff1f5

palette = 0=#bcc0cc
palette = 1=#b00c0c
palette = 2=#2b8217
palette = 3=#9e6900
palette = 4=#3c64b4
palette = 5=#b34295
palette = 6=#3e7174
palette = 7=#5c5f77
palette = 8=#acb0be
palette = 9=#b00c0c
palette = 10=#2b8217
palette = 11=#9e6900
palette = 12=#3c64b4
palette = 13=#b34295
palette = 14=#3e7174
palette = 15=#6c6f85

