#!/bin/bash

set -e

# should be already installed:
# base-devel amd-ucode networkmanager git yadm

common_packages=(
    openssh zsh man-{db,pages}

    # tools
    tmux bat fzf ripgrep zoxide bottom gdu
    lazygit git-delta
    luarocks shellcheck zip unzip
    yt-dlp

    # development
    go python uv rustup

    # apps
    tree-sitter tree-sitter-cli xclip neovim
)

linux_desktop_packages=(
    # nvidia nvidia-settings
    # mesa vulkan-intel intel-media-driver xf86-video-intel

    # system
    gvfs
    reflector ntp

    # Linux desktop
    # xdg-user-dirs xclip

    # laptop
    # light
    # bluez bluez-utils blueman pulseaudio-bluetooth

    # audio
    wireplumber pipewire{,-alsa,-jack,-pulse}
    # qpwgraph carla calf non-mixer pavucontrol

    # gui
    # lightdm{,-gtk-greeter} xorg-{server,apps,server-xephyr}
    # awesome picom rlwrap rofi rofi-emoji xdotool dex
    # lx{appearance,input,session,randr}-gtk3
    # network-manager-applet

    # themes
    # arc-gtk-theme arc-icon-theme capitaine-cursors gtk-engine-murrine
    # kvantum

    # fonts
    noto-fonts{,-cjk,-emoji,-extra} ttf-firacode-nerd ttf-liberation

    # development
    docker
    graphviz 

    # apps
    # redshift python-gobject python-pyxdg
    kitty
    bc
    # feh ksnip
    # pcmanfm-gtk3 engrampa
    discord telegram-desktop
    vlc

    # code

    #wine
    #krita
)

common_aur_packages=(
    fnm-bin
)

linux_desktop_aur_packages=(
    1password
    brave-bin
    # otf-jost
    # kvantum-theme-arc
)

# ---

system_type="$(uname -s)"

if [[ "$(uname -r)" == *"WSL"* ]]; then
    system_type="WSL"
fi

packages=common_packages
aur_packages=common_aur_packages

case "$system_type" in
    "WSL")
        packages=( "${common_packages[@]}" )
        aur_packages=( "${common_aur_packages[@]}" )
        ;;
    "Linux")
        packages=( "${common_packages[@]}" "${linux_desktop_packages[@]}")
        aur_packages=( "${common_aur_packages[@]}" "${linux_desktop_aur_packages[@]}" )
        ;;
    *)
        ;;
esac

# ---

sudo pacman -Sy --needed "${packages[@]}"
yay -S --needed "${aur_packages[@]}"

sudo luarocks install rubato

# ---

# sudo usermod -aG wheel,docker,video "${USER}"
