#!/bin/bash

set -e

setup_ohmyzsh() {
    if  [ ! -d ~/.antidote ]; then
        git clone --depth=1 https://github.com/mattmc3/antidote.git ${ZDOTDIR:-~}/.antidote
    fi
}

setup_vim() {
    (
        cd ~/.config/nvim
	git init
	git remote add origin https://github.com/AstroNvim/AstroNvim
	git fetch --depth 1
	git checkout main
    )
}

setup_ohmyzsh
setup_vim

