#!/usr/bin/env bash

set -e

setup_zsh() {
    if  [[ -d ~/.antidote ]]; then
        return
    fi

    git clone --depth=1 https://github.com/mattmc3/antidote.git "${ZDOTDIR:-~}/.antidote"
}

setup_vim() {
    if [[ -d ~/.config/nvim/.git ]]; then
        return
    fi

    (
        cd ~/.config/nvim
        git init
        git remote add origin https://github.com/AstroNvim/AstroNvim
        git fetch --depth 1
        git checkout main
    )
}

setup_tmux() {
    if [[ -d ~/.tmux/plugins/tpm ]]; then
        return
    fi

    git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
    (
        mkdir -p ~/.tmux/plugins
        cd ~/.tmux/plugins
        ln -s ../../.config/tmux/plugins/tpm ./tpm
    )
}

setup_zsh
setup_vim
setup_tmux
