#!/usr/bin/env bash

set -e

setup_zsh() {
    if  [[ -d ~/.antidote ]]; then
        return
    fi

    git clone --depth=1 https://github.com/mattmc3/antidote.git "${ZDOTDIR:-$HOME}/.antidote"
}

setup_tmux() {
    if [[ ! -d ~/.tmux/plugins/tpm ]]; then
        git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
    fi
    (
        mkdir -p ~/.tmux/plugins
        cd ~/.tmux/plugins
        ln -sf ../../.config/tmux/plugins/tpm ./tpm
    )

    # TODO: does not work if tmux is not running
    tmux run-shell ~/.tmux/plugins/tpm/bindings/install_plugins
}

setup_zsh
setup_tmux
