profile {
    time = 07:00
    temperature = 4000
}

profile {
    time = 09:00
    temperature = 4500
}

profile {
    time = 10:00
    identity = true
}

profile {
    time = 17:00
    temperature = 4500
}

profile {
    time = 20:00
    temperature = 4000
}

profile {
    time = 22:00
    temperature = 3300
}
