# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
  gaps_in = 3
  gaps_out = 6
  border_size = 0
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

animations {
  bezier = easeOutExpo,0.16,1,0.3,1

  animation = windows, 1, 2.5, easeOutExpo
  animation = windowsIn, 1, 2.5, easeOutExpo, popin 90%
  animation = windowsOut, 1, 2.5, easeOutExpo, popin 90%
  animation = fadeIn, 1, 1, easeOutQuint
  animation = fadeOut, 1, 1, easeOutQuint

  # disable animations
  animation = specialWorkspace, 1, 0.5, easeOutQuint, slidevert
}

cursor {
  # hyprsunset compatibility (https://github.com/hyprwm/Hyprland/discussions/12109)
  no_hardware_cursors = 1
}

env = HYPRCURSOR_THEME,posy-white
env = HYPRCURSOR_SIZE,24
